# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2019 Vincent Wiemann <vincent.wiemann@ironai.com>
# Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.

ccflags-y := -O3 -fvisibility=hidden
ccflags-$(CONFIG_TUNNELBRIDGE_DEBUG) += -DDEBUG -g
ccflags-y += -D'pr_fmt(fmt)=KBUILD_MODNAME ": " fmt'

tunnelbridge-y := main.o noise.o client.o device.o peer.o timers.o queueing.o send.o receive.o socket.o peerlookup.o ratelimiter.o cookie.o netlink.o

include $(src)/crypto/Kbuild.include
include $(src)/compat/Kbuild.include

obj-$(if $(KBUILD_EXTMOD),m,$(CONFIG_TUNNELBRIDGE)) := tunnelbridge.o
